version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # 코드 변경 시 바로 반영 (개발 환경에 유용)
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # 코드 변경 시 바로 반영
    environment:
      - CHOKIDAR_USEPOLLING=true # Docker 환경에서 파일 변경 감지를 위한 설정
  db:
    build: ./DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
