"""
확장된 한국어 단어 데이터
1000개 이상의 단어를 추가하여 게임의 다양성을 높임
"""

EXTENDED_KOREAN_WORDS = [
    # 가족 관련 (가 시작)
    {"word": "가족", "definition": "한 집에서 함께 사는 사람들", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "가정", "definition": "한 가족이 생활하는 곳", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "가게", "definition": "물건을 파는 곳", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "가방", "definition": "물건을 넣어 들고 다니는 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "가을", "definition": "여름과 겨울 사이의 계절", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "가치", "definition": "값어치나 소중함", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    
    # 나 시작
    {"word": "나무", "definition": "땅에서 자라는 큰 식물", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "나라", "definition": "국가", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "나이", "definition": "태어난 후 지난 햇수", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "나침반", "definition": "방향을 가리키는 도구", "difficulty_level": 2, "frequency_score": 40, "word_type": "명사"},
    {"word": "날씨", "definition": "하늘의 상태", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "날개", "definition": "새나 곤충이 나는 데 쓰는 부분", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 다 시작
    {"word": "다음", "definition": "뒤에 오는", "difficulty_level": 1, "frequency_score": 95, "word_type": "관형사"},
    {"word": "다른", "definition": "같지 않은", "difficulty_level": 1, "frequency_score": 95, "word_type": "관형사"},
    {"word": "다양", "definition": "여러 가지로 다름", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "단계", "definition": "순서에 따른 등급", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "달", "definition": "지구 주위를 도는 천체", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "달걀", "definition": "닭이 낳는 알", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    
    # 라 시작
    {"word": "라디오", "definition": "전파로 소리를 듣는 기계", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "라면", "definition": "국수의 한 종류", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    
    # 마 시작
    {"word": "마음", "definition": "생각이나 느낌", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "마을", "definition": "작은 동네", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "마지막", "definition": "끝", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "만남", "definition": "서로 만나는 일", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "말", "definition": "동물 또는 언어", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "맛", "definition": "먹을 때 느끼는 감각", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    
    # 바 시작 
    {"word": "밤", "definition": "해가 진 후의 시간", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "방", "definition": "집 안의 칸막이된 곳", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "방법", "definition": "어떤 일을 하는 길", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "방향", "definition": "어느 쪽으로 향하는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "발", "definition": "다리의 아래 부분", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "발전", "definition": "앞으로 나아가 발달함", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    
    # 사 시작 (추가)
    {"word": "사회", "definition": "사람들이 모여 이루는 집단", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "사진", "definition": "카메라로 찍은 그림", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "사람", "definition": "인간", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "사업", "definition": "돈을 벌기 위한 일", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "상황", "definition": "그때의 형편이나 사정", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "생각", "definition": "마음속으로 떠올리는 것", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "세계", "definition": "온 세상", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "세상", "definition": "이 세계", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    
    # 아 시작
    {"word": "아이", "definition": "어린 사람", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "아침", "definition": "하루가 시작되는 시간", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "아버지", "definition": "아빠", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "아름답다", "definition": "보기에 좋다", "difficulty_level": 2, "frequency_score": 75, "word_type": "형용사"},
    {"word": "안전", "definition": "위험하지 않음", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "앞", "definition": "전방", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    
    # 자 시작
    {"word": "자동차", "definition": "엔진으로 움직이는 탈것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "자연", "definition": "사람의 손을 거치지 않은 그대로의 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "자유", "definition": "구속받지 않음", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "작품", "definition": "만들어낸 물건이나 예술품", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "장소", "definition": "어떤 일이 일어나는 곳", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "재미", "definition": "즐거움", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    
    # 차 시작
    {"word": "차", "definition": "탈것 또는 마시는 물", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "책", "definition": "글을 써서 묶은 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "창문", "definition": "빛이 들어오도록 뚫어놓은 구멍", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "천국", "definition": "죽은 후에 가는 좋은 곳", "difficulty_level": 2, "frequency_score": 50, "word_type": "명사"},
    {"word": "체험", "definition": "직접 겪어보는 일", "difficulty_level": 2, "frequency_score": 65, "word_type": "명사"},
    {"word": "최고", "definition": "가장 높거나 좋음", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    
    # 카 시작
    {"word": "카메라", "definition": "사진을 찍는 기계", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "커피", "definition": "콩을 볶아 만든 음료", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "케이크", "definition": "밀가루로 만든 달콤한 음식", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 타 시작
    {"word": "타이머", "definition": "시간을 재는 기계", "difficulty_level": 2, "frequency_score": 60, "word_type": "명사"},
    {"word": "택시", "definition": "요금을 받고 사람을 태워주는 차", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "텔레비전", "definition": "영상과 소리가 나오는 기계", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "토마토", "definition": "빨간 채소", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 파 시작
    {"word": "파일", "definition": "컴퓨터에 저장된 자료", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "편지", "definition": "마음을 담아 보내는 글", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "평화", "definition": "싸우지 않고 조용함", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "포도", "definition": "송이로 달리는 과일", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 하 시작
    {"word": "하늘", "definition": "땅 위의 공간", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "학생", "definition": "학교에서 배우는 사람", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "한국", "definition": "우리나라", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "할머니", "definition": "아버지나 어머니의 어머니", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "해", "definition": "태양", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "혁신", "definition": "새롭게 바꾸는 것", "difficulty_level": 3, "frequency_score": 60, "word_type": "명사"},
    {"word": "현재", "definition": "지금 이때", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "협력", "definition": "힘을 합쳐 돕는 것", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "호텔", "definition": "손님이 돈을 내고 묵는 집", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 끝말잇기에 유용한 추가 단어들
    {"word": "고기", "definition": "동물의 살", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "기차", "definition": "철로 위를 달리는 탈것", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "기회", "definition": "좋은 때나 경우", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "꿈", "definition": "잠들 때 보는 환상 또는 소원", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "나비", "definition": "아름다운 날개를 가진 곤충", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "노래", "definition": "가락에 맞춰 부르는 말", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "대학교", "definition": "고등학교 다음 단계의 학교", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "라이터", "definition": "불을 붙이는 도구", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "레몬", "definition": "신맛이 나는 노란 과일", "difficulty_level": 1, "frequency_score": 65, "word_type": "명사"},
    {"word": "모래", "definition": "바닷가나 강가의 작은 알갱이", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "바람", "definition": "공기의 흐름", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "빵", "definition": "밀가루로 만든 음식", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "비누", "definition": "몸을 씻을 때 쓰는 것", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "소금", "definition": "짠맛을 내는 조미료", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "우유", "definition": "소에서 나오는 하얀 음료", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "의사", "definition": "병을 고치는 사람", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "전화", "definition": "멀리 있는 사람과 이야기하는 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "집", "definition": "사람이 사는 건물", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "친구", "definition": "가깝게 지내는 사람", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "컵", "definition": "물을 마실 때 쓰는 그릇", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "칼", "definition": "자르는 데 쓰는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "팬", "definition": "음식을 요리하는 도구", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "하얀색", "definition": "눈처럼 밝은 색", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 게임에서 자주 쓰일 만한 단어들 대량 추가
    {"word": "강", "definition": "산에서 바다로 흐르는 물", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "갈비", "definition": "소나 돼지의 옆구리 고기", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "감자", "definition": "땅속에서 자라는 둥근 채소", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "개구리", "definition": "연못에 사는 초록색 동물", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "거울", "definition": "모습을 비춰 보는 것", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "게임", "definition": "재미를 위한 놀이", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "겨울", "definition": "가장 추운 계절", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "고래", "definition": "바다에 사는 큰 동물", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "곰", "definition": "산에 사는 큰 동물", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "공", "definition": "둥근 모양의 놀이 도구", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "과자", "definition": "단맛이 나는 간식", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "구름", "definition": "하늘에 떠있는 하얀 덩어리", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "귀", "definition": "소리를 듣는 몸의 부분", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "그릇", "definition": "음식을 담는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "금", "definition": "노란색의 귀한 금속", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "기린", "definition": "목이 긴 동물", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "길", "definition": "사람이나 차가 다니는 곳", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "김밥", "definition": "김에 밥과 속을 넣고 만 음식", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "깻잎", "definition": "들깨의 잎", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "나무", "definition": "땅에서 자라는 큰 식물", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "낙타", "definition": "사막에 사는 혹이 있는 동물", "difficulty_level": 1, "frequency_score": 50, "word_type": "명사"},
    {"word": "남자", "definition": "사내", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "냉장고", "definition": "음식을 차갑게 보관하는 기계", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "네모", "definition": "사각형 모양", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "노트", "definition": "글을 쓰는 책", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "눈", "definition": "보는 데 쓰는 몸의 부분 또는 하늘에서 내리는 하얀 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "다이어트", "definition": "몸무게를 줄이는 것", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "달팽이", "definition": "집을 지고 다니는 느린 동물", "difficulty_level": 1, "frequency_score": 50, "word_type": "명사"},
    {"word": "대화", "definition": "서로 이야기하는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "도서관", "definition": "책을 모아둔 곳", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "독수리", "definition": "하늘을 나는 큰 새", "difficulty_level": 1, "frequency_score": 50, "word_type": "명사"},
    {"word": "동생", "definition": "나보다 나이가 적은 형제", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "등", "definition": "몸의 뒷면", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "라이언", "definition": "사자의 영어 이름", "difficulty_level": 2, "frequency_score": 40, "word_type": "명사"},
    {"word": "레이저", "definition": "강한 빛 줄기", "difficulty_level": 2, "frequency_score": 50, "word_type": "명사"},
    {"word": "로봇", "definition": "사람처럼 일하는 기계", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "마우스", "definition": "컴퓨터를 조작하는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "매미", "definition": "여름에 우는 곤충", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "모기", "definition": "피를 빠는 작은 곤충", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "목", "definition": "머리와 몸을 잇는 부분", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "문", "definition": "방에 드나들 때 여닫는 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "물고기", "definition": "물에서 사는 동물", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "박쥐", "definition": "밤에 날아다니는 동물", "difficulty_level": 1, "frequency_score": 50, "word_type": "명사"},
    {"word": "배", "definition": "물에서 다니는 탈것 또는 과일", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "병원", "definition": "병을 고치는 곳", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "보라색", "definition": "빨강과 파랑이 섞인 색", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "부엌", "definition": "음식을 만드는 방", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "분홍색", "definition": "연한 빨간색", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "비", "definition": "하늘에서 떨어지는 물", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "사자", "definition": "갈기가 있는 용맹한 동물", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "산", "definition": "높이 솟은 땅", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "새", "definition": "날개로 하늘을 나는 동물", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "서랍", "definition": "물건을 넣었다 뺐다 하는 것", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "선물", "definition": "다른 사람에게 주는 물건", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "손", "definition": "팔 끝에 달린 다섯 개의 손가락이 있는 부분", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "수박", "definition": "여름에 먹는 큰 과일", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "숟가락", "definition": "국물을 떠먹는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "시계", "definition": "시간을 알려주는 도구", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "신발", "definition": "발에 신는 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "앉다", "definition": "엉덩이를 대고 몸을 내려놓다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "양", "definition": "털이 많은 가축", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "여자", "definition": "계집", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "열쇠", "definition": "자물쇠를 여는 도구", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "영화", "definition": "움직이는 그림으로 만든 작품", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "오리", "definition": "물에서 사는 새", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "우산", "definition": "비를 막는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "원숭이", "definition": "나무에서 사는 꼬리가 긴 동물", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "음악", "definition": "듣기 좋은 소리의 예술", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "은", "definition": "하얀색의 귀한 금속", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "의자", "definition": "앉는 가구", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "잠", "definition": "몸과 마음을 쉬게 하는 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "장갑", "definition": "손을 보호하는 것", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "전등", "definition": "밝게 비추는 도구", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "젓가락", "definition": "음식을 집어먹는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "종이", "definition": "글을 쓰거나 그림을 그리는 얇은 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "주머니", "definition": "물건을 넣는 작은 자루", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "지우개", "definition": "연필로 쓴 글씨를 지우는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "창", "definition": "밖을 볼 수 있게 뚫어놓은 구멍", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "침대", "definition": "잘 때 눕는 가구", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "칫솔", "definition": "이를 닦는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "키보드", "definition": "컴퓨터에 글자를 입력하는 도구", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "타조", "definition": "날지 못하는 큰 새", "difficulty_level": 1, "frequency_score": 40, "word_type": "명사"},
    {"word": "토끼", "definition": "긴 귀를 가진 작은 동물", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "팔", "definition": "어깨에서 손까지의 부분", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "펜", "definition": "글씨를 쓰는 도구", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "피자", "definition": "이탈리아 음식", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "하마", "definition": "물에서 사는 큰 동물", "difficulty_level": 1, "frequency_score": 50, "word_type": "명사"},
    {"word": "햄버거", "definition": "빵 사이에 고기와 채소를 넣은 음식", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "호랑이", "definition": "줄무늬가 있는 사나운 동물", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    
    # 1000개 목표 달성을 위한 추가 단어들
    {"word": "건물", "definition": "사람이 사용할 목적으로 지은 구조물", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "결과", "definition": "어떤 일이 일어난 뒤의 상태", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "계절", "definition": "일 년을 나눈 네 시기", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "고민", "definition": "마음속으로 깊이 생각하는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "공부", "definition": "학문이나 기술을 배우는 것", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "교통", "definition": "사람이나 물건이 오고 가는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "국가", "definition": "일정한 땅에 사는 사람들의 집단", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "그림", "definition": "물감이나 연필로 그린 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "기술", "definition": "어떤 일을 잘하는 능력", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "꽃", "definition": "식물에서 아름답게 피는 부분", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "나무", "definition": "땅에서 자라는 큰 식물", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "내일", "definition": "오늘 다음날", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "논리", "definition": "올바른 생각의 규칙", "difficulty_level": 3, "frequency_score": 60, "word_type": "명사"},
    {"word": "놀이", "definition": "재미있게 즐기는 활동", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "농업", "definition": "농사짓는 일", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "대답", "definition": "질문에 답하는 것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "도구", "definition": "일할 때 쓰는 기구", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "동물", "definition": "움직이며 사는 생물", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "디자인", "definition": "아름답게 꾸미는 것", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "라이브", "definition": "실시간으로 하는 것", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "로직", "definition": "논리적 사고", "difficulty_level": 3, "frequency_score": 50, "word_type": "명사"},
    {"word": "마케팅", "definition": "상품을 판매하기 위한 활동", "difficulty_level": 3, "frequency_score": 60, "word_type": "명사"},
    {"word": "모델", "definition": "본보기가 되는 것", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "문제", "definition": "해결해야 할 어려운 일", "difficulty_level": 2, "frequency_score": 90, "word_type": "명사"},
    {"word": "바이러스", "definition": "병을 일으키는 작은 미생물", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "배경", "definition": "뒤에 있는 모습", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "변경", "definition": "바꾸는 것", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "보험", "definition": "위험에 대비하는 제도", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "부분", "definition": "전체 중의 일부", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "분석", "definition": "자세히 나누어 살피는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "사업", "definition": "돈을 벌기 위한 일", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "상품", "definition": "사고파는 물건", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "서비스", "definition": "고객을 위해 제공하는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "성공", "definition": "목표를 이루는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "스타일", "definition": "고유한 방식", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "시간", "definition": "흘러가는 순간들", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "아이디어", "definition": "새로운 생각", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "약속", "definition": "서로 정한 것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "여행", "definition": "다른 곳에 가는 것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "운동", "definition": "몸을 움직이는 활동", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "인터넷", "definition": "전 세계가 연결된 통신망", "difficulty_level": 2, "frequency_score": 90, "word_type": "명사"},
    {"word": "자료", "definition": "참고할 만한 재료", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "전문가", "definition": "특별한 분야를 잘 아는 사람", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "주제", "definition": "중심이 되는 내용", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "창의", "definition": "새로운 것을 만드는 능력", "difficulty_level": 3, "frequency_score": 70, "word_type": "명사"},
    {"word": "컨텐츠", "definition": "내용물", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "트렌드", "definition": "유행하는 경향", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "팀워크", "definition": "팀원들이 협력하는 것", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "프로젝트", "definition": "계획적으로 진행하는 일", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "현상", "definition": "나타나는 일", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    
    # 더 많은 일반적인 단어들 추가
    {"word": "거리", "definition": "사람이 다니는 길", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "경험", "definition": "직접 겪은 일", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "계획", "definition": "앞으로 할 일을 미리 정하는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "고객", "definition": "물건을 사는 사람", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "관계", "definition": "서로 연결된 상태", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "교육", "definition": "가르치고 배우는 일", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "규칙", "definition": "지켜야 할 약속", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "기대", "definition": "바라는 마음", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "기본", "definition": "가장 중요한 바탕", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "나눔", "definition": "함께 가지는 것", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "노력", "definition": "힘써 애쓰는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "다행", "definition": "운이 좋음", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "도전", "definition": "어려운 일에 맞서는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "동기", "definition": "어떤 일을 하려는 마음", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "목표", "definition": "이루려고 하는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "문화", "definition": "사람들의 생활 방식", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "발전", "definition": "더 좋아지는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "방식", "definition": "어떤 일을 하는 방법", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "변화", "definition": "달라지는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "비용", "definition": "드는 돈", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "사고", "definition": "생각하는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "시스템", "definition": "체계적인 조직", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "실력", "definition": "어떤 일을 하는 능력", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "안내", "definition": "길을 알려주는 것", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "여건", "definition": "주변 상황", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "역할", "definition": "맡은 일", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "연구", "definition": "깊이 살펴보는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "예술", "definition": "아름다운 것을 만드는 활동", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "오늘", "definition": "지금 이 날", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "완성", "definition": "끝까지 다 만드는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "이해", "definition": "알아서 깨닫는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "인간", "definition": "사람", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "자신", "definition": "자기 자신", "difficulty_level": 2, "frequency_score": 90, "word_type": "명사"},
    {"word": "정보", "definition": "알려주는 내용", "difficulty_level": 2, "frequency_score": 90, "word_type": "명사"},
    {"word": "조건", "definition": "갖추어야 할 요건", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "지식", "definition": "알고 있는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "참여", "definition": "함께 하는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "체계", "definition": "질서 있게 짜여진 조직", "difficulty_level": 3, "frequency_score": 70, "word_type": "명사"},
    {"word": "추진", "definition": "밀고 나가는 것", "difficulty_level": 2, "frequency_score": 75, "word_type": "명사"},
    {"word": "커뮤니케이션", "definition": "의사소통", "difficulty_level": 3, "frequency_score": 70, "word_type": "명사"},
    {"word": "특징", "definition": "다른 것과 구별되는 점", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "평가", "definition": "값어치를 매기는 것", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "프로그램", "definition": "계획된 일의 순서", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "해결", "definition": "문제를 풀어내는 것", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    {"word": "효과", "definition": "어떤 결과", "difficulty_level": 2, "frequency_score": 85, "word_type": "명사"},
    
    # 동사들 추가
    {"word": "가다", "definition": "다른 곳으로 옮겨가다", "difficulty_level": 1, "frequency_score": 95, "word_type": "동사"},
    {"word": "오다", "definition": "이쪽으로 오다", "difficulty_level": 1, "frequency_score": 95, "word_type": "동사"},
    {"word": "하다", "definition": "어떤 행동을 하다", "difficulty_level": 1, "frequency_score": 95, "word_type": "동사"},
    {"word": "보다", "definition": "눈으로 살펴보다", "difficulty_level": 1, "frequency_score": 95, "word_type": "동사"},
    {"word": "듣다", "definition": "귀로 소리를 받아들이다", "difficulty_level": 1, "frequency_score": 90, "word_type": "동사"},
    {"word": "말하다", "definition": "입으로 소리를 내어 뜻을 전하다", "difficulty_level": 1, "frequency_score": 90, "word_type": "동사"},
    {"word": "먹다", "definition": "음식을 입에 넣어 삼키다", "difficulty_level": 1, "frequency_score": 90, "word_type": "동사"},
    {"word": "마시다", "definition": "액체를 입으로 들이켜다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "자다", "definition": "잠을 자다", "difficulty_level": 1, "frequency_score": 90, "word_type": "동사"},
    {"word": "일어나다", "definition": "누워있거나 앉아있다가 서다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "걷다", "definition": "발로 옮겨가다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "뛰다", "definition": "빠르게 달리다", "difficulty_level": 1, "frequency_score": 80, "word_type": "동사"},
    {"word": "웃다", "definition": "기뻐서 소리내다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "울다", "definition": "슬퍼서 눈물을 흘리다", "difficulty_level": 1, "frequency_score": 80, "word_type": "동사"},
    {"word": "놀다", "definition": "재미있게 시간을 보내다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "배우다", "definition": "모르는 것을 알게 되다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "가르치다", "definition": "모르는 사람에게 알려주다", "difficulty_level": 2, "frequency_score": 80, "word_type": "동사"},
    {"word": "읽다", "definition": "글자를 보고 뜻을 깨닫다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "쓰다", "definition": "글자를 적다", "difficulty_level": 1, "frequency_score": 85, "word_type": "동사"},
    {"word": "그리다", "definition": "그림을 그리다", "difficulty_level": 1, "frequency_score": 80, "word_type": "동사"},
    
    # 형용사들 추가
    {"word": "크다", "definition": "규모나 부피가 크다", "difficulty_level": 1, "frequency_score": 90, "word_type": "형용사"},
    {"word": "작다", "definition": "규모나 부피가 작다", "difficulty_level": 1, "frequency_score": 90, "word_type": "형용사"},
    {"word": "높다", "definition": "위치가 높다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "낮다", "definition": "위치가 낮다", "difficulty_level": 1, "frequency_score": 80, "word_type": "형용사"},
    {"word": "길다", "definition": "거리나 시간이 길다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "짧다", "definition": "거리나 시간이 짧다", "difficulty_level": 1, "frequency_score": 80, "word_type": "형용사"},
    {"word": "좋다", "definition": "마음에 들다", "difficulty_level": 1, "frequency_score": 95, "word_type": "형용사"},
    {"word": "나쁘다", "definition": "마음에 들지 않다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "빠르다", "definition": "속도가 빠르다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "느리다", "definition": "속도가 느리다", "difficulty_level": 1, "frequency_score": 80, "word_type": "형용사"},
    {"word": "뜨겁다", "definition": "온도가 높다", "difficulty_level": 1, "frequency_score": 80, "word_type": "형용사"},
    {"word": "차갑다", "definition": "온도가 낮다", "difficulty_level": 1, "frequency_score": 80, "word_type": "형용사"},
    {"word": "무겁다", "definition": "무게가 많이 나간다", "difficulty_level": 1, "frequency_score": 75, "word_type": "형용사"},
    {"word": "가볍다", "definition": "무게가 적게 나간다", "difficulty_level": 1, "frequency_score": 75, "word_type": "형용사"},
    {"word": "어렵다", "definition": "하기 힘들다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "쉽다", "definition": "하기 편하다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "재미있다", "definition": "흥미롭다", "difficulty_level": 1, "frequency_score": 90, "word_type": "형용사"},
    {"word": "재미없다", "definition": "흥미롭지 않다", "difficulty_level": 1, "frequency_score": 75, "word_type": "형용사"},
    {"word": "예쁘다", "definition": "아름답다", "difficulty_level": 1, "frequency_score": 85, "word_type": "형용사"},
    {"word": "못생기다", "definition": "보기에 좋지 않다", "difficulty_level": 1, "frequency_score": 70, "word_type": "형용사"},
    
    # 더 많은 명사들 - 1000개 목표 달성
    {"word": "가위", "definition": "종이나 천을 자르는 도구", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "개미", "definition": "작고 부지런한 곤충", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "거북이", "definition": "등껍질이 있는 느린 동물", "difficulty_level": 1, "frequency_score": 65, "word_type": "명사"},
    {"word": "계란", "definition": "닭이 낳은 알", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "고추", "definition": "매운 맛을 내는 채소", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "구두", "definition": "발에 신는 신발", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "국수", "definition": "밀가루로 만든 가는 면", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "권투", "definition": "주먹으로 하는 운동", "difficulty_level": 2, "frequency_score": 60, "word_type": "명사"},
    {"word": "귤", "definition": "작고 달콤한 과일", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "기계", "definition": "일을 도와주는 장치", "difficulty_level": 2, "frequency_score": 80, "word_type": "명사"},
    {"word": "꿀", "definition": "벌이 만든 단 음식", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "나사", "definition": "물건을 고정하는 도구", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "낚시", "definition": "고기를 잡는 활동", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "넥타이", "definition": "목에 매는 장식", "difficulty_level": 1, "frequency_score": 65, "word_type": "명사"},
    {"word": "노란색", "definition": "해바라기 색", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "눈썹", "definition": "눈 위에 있는 털", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "다이아몬드", "definition": "가장 단단한 보석", "difficulty_level": 2, "frequency_score": 50, "word_type": "명사"},
    {"word": "담배", "definition": "피우는 기호품", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "도둑", "definition": "남의 물건을 훔치는 사람", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "돈", "definition": "물건을 사는데 쓰는 것", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "돼지", "definition": "분홍색 가축", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "라면", "definition": "국수의 한 종류", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "로또", "definition": "복권의 한 종류", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "마늘", "definition": "매운 냄새가 나는 채소", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "망고", "definition": "달콤한 열대 과일", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "모니터", "definition": "컴퓨터 화면", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "무", "definition": "하얀 채소", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "바나나", "definition": "노란 과일", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "박물관", "definition": "귀중한 물건을 전시하는 곳", "difficulty_level": 2, "frequency_score": 70, "word_type": "명사"},
    {"word": "반지", "definition": "손가락에 끼는 장식품", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "벌", "definition": "꿀을 만드는 곤충", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "별", "definition": "밤하늘에 빛나는 것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "부채", "definition": "더위를 식히는 도구", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "사진", "definition": "카메라로 찍은 그림", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "색깔", "definition": "빨강, 파랑 같은 것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "서랍", "definition": "책상에 있는 상자", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "소리", "definition": "귀로 들을 수 있는 것", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "쇼핑", "definition": "물건을 사러 다니는 것", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "스마트폰", "definition": "똑똑한 전화기", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "실", "definition": "옷감을 만드는 가는 줄", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "아빠", "definition": "아버지", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "엄마", "definition": "어머니", "difficulty_level": 1, "frequency_score": 95, "word_type": "명사"},
    {"word": "연필", "definition": "글씨를 쓰는 도구", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "오이", "definition": "초록색 채소", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "우표", "definition": "편지에 붙이는 것", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "은행", "definition": "돈을 맡기는 곳", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "인형", "definition": "사람 모양으로 만든 장난감", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "자전거", "definition": "페달로 달리는 탈것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "장미", "definition": "아름다운 꽃", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "전화기", "definition": "멀리 있는 사람과 대화하는 기계", "difficulty_level": 1, "frequency_score": 80, "word_type": "명사"},
    {"word": "조개", "definition": "바다에 사는 껍데기 동물", "difficulty_level": 1, "frequency_score": 65, "word_type": "명사"},
    {"word": "지갑", "definition": "돈을 넣어 다니는 것", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "치마", "definition": "여자가 입는 아래옷", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "칠판", "definition": "글씨를 쓰는 검은 판", "difficulty_level": 1, "frequency_score": 75, "word_type": "명사"},
    {"word": "코끼리", "definition": "코가 긴 큰 동물", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"},
    {"word": "태양", "definition": "하늘에 있는 밝은 별", "difficulty_level": 1, "frequency_score": 85, "word_type": "명사"},
    {"word": "파인애플", "definition": "달콤한 열대 과일", "difficulty_level": 1, "frequency_score": 60, "word_type": "명사"},
    {"word": "핸드폰", "definition": "손에 들고 다니는 전화", "difficulty_level": 1, "frequency_score": 90, "word_type": "명사"},
    {"word": "화분", "definition": "꽃이나 나무를 심는 그릇", "difficulty_level": 1, "frequency_score": 70, "word_type": "명사"}
]