name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 수동 실행 가능

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Server
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        # SSH 키 설정
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # 서버에 배포
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
          cd /path/to/kkua
          git pull origin main
          ./deploy.sh production
        EOF
    
    - name: Health Check
      run: |
        sleep 30
        curl -f https://your-domain.com/health || exit 1
        echo "✅ Deployment successful!"