name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # 간단한 PR 체크 - 브랜치 이름만 확인
  check-branch:
    name: Check Branch
    runs-on: ubuntu-latest
    steps:
    - name: Check branch naming
      run: |
        branch="${GITHUB_HEAD_REF}"
        # feature/, fix/, hotfix/, release/, docs/ 허용
        if [[ ! "$branch" =~ ^(feature|fix|hotfix|release|docs)/.+ ]]; then
          echo "⚠️ Branch name: '$branch'"
          echo "✅ Recommended prefixes: feature/, fix/, hotfix/, release/, docs/"
          # 경고만 하고 실패하지 않음
        fi